// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PRIMERA_API.Data;

#nullable disable

namespace PRIMERA_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416003322_Colores")]
    partial class Colores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("PRIMERA_API.Models.Tabla2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabla2");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "Rojo"
                        },
                        new
                        {
                            Id = 2,
                            Color = "Verde"
                        },
                        new
                        {
                            Id = 3,
                            Color = "Azul"
                        });
                });

            modelBuilder.Entity("PRIMERA_API.Models.tabla1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tabla1");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Garcia",
                            Nombre = "Fabian"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Dominguez",
                            Nombre = "Paula"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Cruz",
                            Nombre = "Dilan"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
